name: Publish

on:
  push:
    branches-ignore:
      - gh-pages # excludes gh-pages
  pull_request:
    branches-ignore:
      - gh-pages # excludes gh-pages

jobs:
  Publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodeModules-

      - name: Install dependencies 📦️
        if: steps.cache-node-modules.outputs.cache-hit != true
        run: npm install

      - name: npm deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "xianzhe.guo"
          git config --global user.email "guo90962@gmail.com"
          npm run deploy
